### ISSUE TITLE
Todo before going public...

### ISSUE THREAD

**Issue by jesseleite** [jesseleite/nvim-noirbuddy#1]
- [x] Finish picking colors for `default` preset
    - [x] Maybe put together a few extra presets
- [x] Finish basic highlighting in `theme.lua`
    - [x] Highlight treesitter syntax capture groups by default (ie. `@string.special`)
    - ~[ ] Detect nvim version and fallback to old capture groups for older versions (ie. `SpecialChar`)~
        - Don't need to do this. We highlight both, and treesitter automatically takes precedence.
- [x] Font options (should default to false)~~
    - [x] Bold
    - [x] Italics
    - [x] Underlines
    - [x] Undercurls
- [ ] Test in following languages
    - [x] Lua
    - [x] Vimscript
    - [x] Javascript
    - [x] Typescript
    - [x] JSX/TSX
    - [x] JSON
    - [x] YAML
    - [x] HTML
    - [x] CSS
    - [x] PHP
    - [x] Rust
    - [x] Markdown
    - [ ] Any others?
- [x] Finish readme
    - [x] Screenshots for each preset
    - [x] Show installation and configuration examples
- [x] Export themes or preset colors (?) for third party plugins (such as lualine)
